export const add = () => ({type: 'ADD'})
export const fetchData = data => ({type:'DATA_FETCHING', payload: data})
export const setFindTime = data => ({type:'FIND_TIME', payload: data})
export const setFindOddOrEven = data => ({type:'FIND_ODD_OR_EVEN', payload: data})
export const dataAdding = data => ({type: 'DATA_ADDING', payload: data})